export enum DisciplinaEnum {
  matematica = 'Matemática',
  geografia = 'Geografia',
  portugues = 'Português',
  historia = 'História',
  ciencias = 'Ciências',
  fisica = 'Física',
  quimica = 'Química',
  biologia = 'Biologia',
  linguaPortuguesa = 'Língua Portuguesa',
  ingles = 'Inglês',
  espanhol = 'Espanhol',
  artes = 'Artes',
  musica = 'Música',
  sociologia = 'Sociologia',
  filosofia = 'Filosofia',
  literatura = 'Literatura',
}
