export enum TurmaEnum {
  maternal = 'maternal',
  infantil1 = 'infantil 1',
  infantil2 = 'infantil 2',
  infantil3 = 'infantil 3',
  ano1 = '1º ano',
  ano2 = '2º ano',
  ano3 = '3º ano',
  ano4 = '4º ano',
  ano5 = '5º ano',
  ano6 = '6º ano',
  ano7 = '7º ano',
  ano8 = '8º ano',
  ano9 = '9º ano',
  medio1 = '1º médio',
  medio2 = '2º médio',
  medio3 = '3º médio',
}
